### ISSUE TITLE
Typechecking fails (including JSX issues)

### ISSUE THREAD

**Issue by hashmal** [zsakowitz/ithkuil#1]
When I run `tsc` on my project, the `node_modules/@sznout/ithkuil` gets lumped in, no matter how I exclude it from my tsconfig.json file.

It results in 90 errors, for which I'll quote only the first one for brievety:

```
node_modules/@zsnout/ithkuil/generate/adjunct/index.ts:112:63 - error TS2554: Expected 0-1 arguments, but got 2.

112   throw new Error("Unrecognized adjunct: '" + adjunct + "'.", {
                                                                  ~
113     cause: adjunct,
    ~~~~~~~~~~~~~~~~~~~
114   })
    ~~~
```

Note that if I update my tsconfig.json with the README recommendation, i.e.

```
{
  "compilerOptions": {
    ...
    "jsx": "react-jsx",
    "jsxImportSource": "@zsnout/ithkuil/script"
    ...
  }
}
```

The errors climb up to 145.

During my investigation, I downloaded @zsnout/ithkuil directly to try to build it independently. I still get tons of errors (176 or so).

I'd like to provide more information, but I'm left completely clueless with my situation. Any ideas?

**Comment by zsakowitz** [comment]
I've run into the same thing when integrating it with projects of my own. I think it's that I'm currently uploading all the original TS files, when I should be generating declarations so the errors get suppressed. The package itself does build fine on its own and doesn't have type errors, but it can easily easily fail under slightly different tsconfigs. I'll try uploading a version with only `.js` and `.d.ts` files right now to see what happens.

**Comment by zsakowitz** [comment]
I'll let you know once I think it's resolved.

**Comment by zsakowitz** [comment]
I've tried uploading a new version `0.1.117` which should no longer have a `tsconfig.json` or any `.ts` files; just `.d.ts` files. Hopefully that'll get rid of the errors; let me know!

**Comment by hashmal** [comment]
Indeed, I run into it the first time when I added @zsnout/ithkuil as a dependency of one of my projects. Strangely, the typechecker lumps all the lib no matter how I configure the project to ignore `node_modules`. So I decided to pull the lib itself to investigate and hopefully to contribute, only to be met with the same errors… I wish I could narrow down the problem to help you, but as of now, I'm clueless…

The good news is that, despite all the errors and warnings, the lib works as intended and I'm having a blast using it 🤩

**Comment by zsakowitz** [comment]
Glad it works!

I can't tell from your message if you're still getting TypeScript errors after installing `0.1.117` (code is on the [`decomposer` branch](https://github.com/zsakowitz/ithkuil/tree/decomposer), but the package is public on NPM). Do they still exist?

**Comment by hashmal** [comment]
I wrote my last message 3 minutes apart from yours; since then, after upgrading, my project relying on this library doesn't suffer from any more errors, good job!

But I also tried running `npm install` on the `decomposer` branch of your project itself, and the exact errors remain. Overall this is still an great improvement, thank you for your quick replies!

**Comment by zsakowitz** [comment]
It seems to be an error with the JSX library missing type declarations. Try cloning the latest version of `decomposer`; I believe all errors are now resolved.

**Comment by zsakowitz** [comment]
Oh, and make sure that `@zsnout/ithkuil-jsx` updates to `0.1.3`.

**Comment by hashmal** [comment]
Just pulled your changes for both my fork and my own repos relying on this lib: works like a charm! It's always a bliss to set up some code/repos/dependencies and have 0 errors when putting everything together 🥰

Thank you for your help, I didn't expect such quick replies, let alone stuff being fixed in literally minutes!

**Comment by zsakowitz** [comment]
You're welcome! I'm so glad somebody is using the library; I was very unsure whether the NPM download counts are real or from bots. Nice to know at least one is legitimate!

**Comment by hashmal** [comment]
Yeah, npm downloads are somewhat abstract, like on every other platform I know (I have a Ruby library that still get hundreds of installs, despite not having updated it in 10 years hahaha)

And damn, you can be sure I’’m a legitimate user… on top of being a linguistics nerd, I have an Ithkuil word tattoo I created using one of your online tools. I plan to do more, hence why I'm working on my own code (that I will share, open source with a permissive license, as soon as it is stable enough).

Let’s keep in touch, an again, congratulations for the amount of work you’ve put in so far!

Jérémy

**Comment by zsakowitz** [comment]
Very neat for the tattoo. Excited to see what you work on!

**Comment by hashmal** [comment]
Thanks!

While I didn’t release my work on Github yet, I can share a few things with you:

When I got the tattoo, I did not code anything yet, I admit I just used https://v8.zsnout.com/ithkuil/script/ to obtain characters separately and assemble them by hand in a vector illustration app. In the process I still managed to include a mistake, but oh well… It’s minor enough that it’ll be fixable in the future.

At the time I was ROOTING for an Ithkuil library, but I couldn’t find anything. Now I assume that "zsakowitz" and "zsnout" both refer to you… am I correct? If so, adding links to your GitHub repos would be very useful for at least some poeple… Afterall, I implemented all Ithkuil romanization rules on my own before stumbling upon @zsnout/ithkuil… I think it’s better to cooperate than reinvent the wheel, right? ;)

So, here is a picture of the tattoo:

￼

And a few screenshots of the app I’m currently working on:

￼
￼
￼

I don’t have a clear plan of what I want to achieve, I do this mainly for the fun and challenge. I will let you know when the code is available publicly for sure! For now the features include:
- building formatives by filling a form representing slots
- same for referentials
- stacking multiple words on a line and reordering them
- parsing a sentence (this is really just a a wrapper around your work, to be honest)
- full-text search over roots and affixes
- exploring the lexicon based on the structure of the "official" Lexicon PDF
- IPA output for every word, hopping I’ll find a tool suitable enough to pronounce everything (I played a bit with Amazon Polly, but I’m not satisfied with the glottal stops and the stressed syllables…)

I also spent some time exploring your code, but I must admit I have a bit of trouble wrapping my mind around it. It’s not a criticism in any way, I see coding as a mean of expression so it’s natural to have many different ways of coding… And I still wonder when and how you’ve been able to be so productive. kudos!

Oh, and I cannot commit formally on anything, but if you need help on @zsnout/ithkuil (even if it’s just documentation or unit testing), just let me know and I’ll tell you if that’s compatible with my schedule.

Kindly,

Jérémy

**Comment by zsakowitz** [comment]
Yes, @zsakowitz and @zSnout are both me. zSnout was originally designated to hold website-related things, but they've slightly blurred over the years.

The photos don't seem to have uploaded.

Most of my work too is for fun and challenge. Always great to work on projects that you're interested in, no?

Word builders are a great idea; I haven't yet found a format I'm totally satisfied with. I've tried [one somewhat arranged by slot structure / scope order](https://zsnout.com/ithkuil/generate/formative), [one based on editing script characters (mostly incomplete)](https://zsnout.com/ithkuil/generate/script), [one where you type in glosses](https://zsnout.com/ithkuil/kit), but they all have their issues (the first one's problem is mainly that it doesn't support the majority of Ithkuil nor is the search functionality very intuitive; the second one's... well I need to work on that one more to judge it; the third one's worst fault is that nothing is explained, I think). Something which lets you drag to reorder scope sounds fascinating, and very intuitive! And hearing Ithkuil spoken aloud would be very helpful for learning and music purposes, I think. Very interesting!

My code style is an interesting one. I think a third of it comes from relying on TypeScript to be a strong guide, another third from battling against TypeScript when its decisions are faulty, and the final third from not planning my code structure enough. But there are other elements too, I'm sure.

Regarding time: some of it comes at the cost of sleep, some of it comes from breaks between classes (still in school for now), and some of it comes from motivation to work and ideas trumping anything else I'd want to do.

Thanks for the offer for help!

**Comment by hashmal** [comment]
Oh, too bad for the pictures… here is another attempt, I uploaded them on Imgur: https://imgur.com/a/HnknAP0 (feels a bit old-school haha)

I checked your link, you’re really outputting a huge amount of work… As for the "word-builders" thing, I explored a few ideas on paper but in the end my app follows the 10-slots structure of formatives as explained on the official documentation and on Yuorb. I always feel like there could be a better way, but for now I considerer it "good enough". at least, the forms match the official documentation, which is a good thing, I think.

Speaking of Yuorb, I’m on Discord (e.g. https://discord.com/channels/131937038139260928/131937038139260928 ) under the pseudonym "hashmal", if you want to chat over there.

In any case, as you said the topic is wildly interesting, and I suppose it’s a reason my project is all over the place (I didn’t even write a single a line of code aboud Adjuncts, for example haha).

As for actually speaking Ithkuil (or songs, or poetry), I think that’s another "meta" level for which I’m not ready for (for instance, rhymes could easily be boring since the last phomenes of formatives indicate case…) but other features of the languages, including glottal stops, stress and gemination, could potentially open a new world of creativity ;)

Our different "style" of coding is certainly due in part to our respective experiences… I’ve been working as a developper for around 14 years, and I admit I picked a lot of "corporate coding practices" along the way. It was very unusual for me to read how you coded "PartialFormative" and others, yet it felt very refreshing at the same time: I wouldn’t have been able to come up with such solutions!

Kindly, hoping to chat with you soon

Jérémy

**Comment by zsakowitz** [comment]
Oh, nice! The site looks like it's coming along well; nice work!

Yeah, the slot structure is more representative of how Ithkuil is pronounced than any grammar. Although it does at least mostly follow scoping order (until shortcuts get involved), which is nice.

Messaged you there!

Ah yeah, adjuncts, while very cool, are somewhat a pain to deal with. Had to invent a Slot XI for the purposes of the script generator (for adjuncts which take scope over the entire word), and most of the special-casing in it is for adjuncts (especially registers, since written and spoken, they are quite different).

Mm, true. I have no idea how I'd make nice-sounding songs, but those all do sound like great places to start. And yeah, rhymes simply with cases might be boring. Perhaps trying to match consonant forms instead?

Aaaa, all the formative types are a mess. I tried rewriting this project in Rust once and modeled the type-level design after the idea of "make invalid states unrepresentable", and it ended up with me having five to seven levels of nested structs and union types just to make everything work out. Such a pain, and I didn't even use them very much (all the actual code for generation and parsing uses a different layer of less strict types).

**Comment by hashmal** [comment]
Thanks mate :)

Before I found your lib, I was romanizing formatives in steps, each step being a specific class (like "'Initial", "Gemination", "Shortcut", "Stress"), each class being able to preserve its slots so I was able to display a table/graph of the complete process of Formative -> Romanized transformation. That fixed the issue of shortcuts being confusing ;)

I did not read the rules governing Adjuncts seriously yet, I dread it a little haha.

As for Rust, I love that language and used it extensively a few years ago to build a realtime audio engine. But while the language shines for systems programming, it becomes a nightmare when you want to create a full app. And yes, at some point I found myself with a mess of nested structs… that had become so large it wouldn’t fit on the callstack, to the point I was getting SEGFAULTS… in Rust! 🤣

TypeScript is far from perfcet, but it’s still very useful, let’s be pragmatic.

Will check Discord today, TTYL!
